require 'Items/ProceduralDistributions'

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].junk.items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].junk.items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.1);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 1);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 1);
table.insert(ProceduralDistributions.list["JanitorMisc"].items, "Autotsar.ATATuningFordMustang");
table.insert(ProceduralDistributions.list["JanitorMisc"].items, 1);

-- Base.ATAMustangFendersWideItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustangFendersWideItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustangFendersWideItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATAMustangFendersWideItem");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAMustangFendersWideItem");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Autotsar.ATAMustangFendersWideItem");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);
-- Base.ATAMustangSkirtsSideItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustangSkirtsSideItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustangSkirtsSideItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATAMustangSkirtsSideItem");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAMustangSkirtsSideItem");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Autotsar.ATAMustangSkirtsSideItem");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);
-- Base.ATAMustangSpoilerFrontItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustangSpoilerFrontItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustangSpoilerFrontItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATAMustangSpoilerFrontItem");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAMustangSpoilerFrontItem");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Autotsar.ATAMustangSpoilerFrontItem");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);

-- Base.ATAMustangSpoilerRear1Item
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustangSpoilerRear1Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustangSpoilerRear1Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Autotsar.ATAMustangSpoilerRear1Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Autotsar.ATAMustangSpoilerRear1Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAMustangSpoilerRear1Item");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 1);

-- Base.ATAMustangSpoilerRear2Item
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAMustangSpoilerRear2Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAMustangSpoilerRear2Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Autotsar.ATAMustangSpoilerRear2Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Autotsar.ATAMustangSpoilerRear2Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAMustangSpoilerRear2Item");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 1);
