--***********************************************************
--**                    THE INDIE STONE                    **
--***********************************************************

local group = AttachedLocations.getGroup("Human")

group:getOrCreateLocation("Schoolbag Gear"):setAttachmentName("schoolbag_gear")
group:getOrCreateLocation("Schoolbag Canteen"):setAttachmentName("schoolbag_canteen")
group:getOrCreateLocation("Schoolbag Walkie"):setAttachmentName("schoolbag_walkie")
group:getOrCreateLocation("Schoolbag Bottle"):setAttachmentName("schoolbag_bottle")
group:getOrCreateLocation("Schoolbag Gas"):setAttachmentName("schoolbag_gas")
group:getOrCreateLocation("Hikingbag Gear"):setAttachmentName("hikingbag_gear")
group:getOrCreateLocation("Hikingbag Canteen"):setAttachmentName("hikingbag_canteen")
group:getOrCreateLocation("Hikingbag Walkie"):setAttachmentName("hikingbag_walkie")
group:getOrCreateLocation("Hikingbag Bottle"):setAttachmentName("hikingbag_bottle")
group:getOrCreateLocation("Hikingbag Gas"):setAttachmentName("hikingbag_gas")
group:getOrCreateLocation("Hikingbag Left Gear"):setAttachmentName("hikingbag_left_gear")
group:getOrCreateLocation("Hikingbag Left Canteen"):setAttachmentName("hikingbag_left_canteen")
group:getOrCreateLocation("Hikingbag Left Tool1"):setAttachmentName("hikingbag_left_tool1")
group:getOrCreateLocation("Hikingbag Left Tool2"):setAttachmentName("hikingbag_left_tool2")
group:getOrCreateLocation("Hikingbag Left Tool3"):setAttachmentName("hikingbag_left_tool3")
group:getOrCreateLocation("Hikingbag Left Walkie"):setAttachmentName("hikingbag_left_walkie")
group:getOrCreateLocation("Hikingbag Left Bottle"):setAttachmentName("hikingbag_left_bottle")
group:getOrCreateLocation("ALICEpack Gear"):setAttachmentName("alicepack_gear")
group:getOrCreateLocation("ALICEpack Canteen"):setAttachmentName("alicepack_canteen")
group:getOrCreateLocation("ALICEpack Walkie"):setAttachmentName("alicepack_walkie")
group:getOrCreateLocation("ALICEpack Bottle"):setAttachmentName("alicepack_bottle")
group:getOrCreateLocation("ALICEpack Gas"):setAttachmentName("alicepack_gas")
group:getOrCreateLocation("ALICEpack Gear Right"):setAttachmentName("alicepack_gear_right")
group:getOrCreateLocation("ALICEpack Canteen Right"):setAttachmentName("alicepack_canteen_right")
group:getOrCreateLocation("ALICEpack Walkie Right"):setAttachmentName("alicepack_walkie_right")
group:getOrCreateLocation("ALICEpack Bottle Right"):setAttachmentName("alicepack_bottle_right")
group:getOrCreateLocation("ALICEpack Gear Left"):setAttachmentName("alicepack_gear_left")
group:getOrCreateLocation("ALICEpack Canteen Left"):setAttachmentName("alicepack_canteen_left")
group:getOrCreateLocation("ALICEpack Walkie Left"):setAttachmentName("alicepack_walkie_left")
group:getOrCreateLocation("ALICEpack Bottle Left"):setAttachmentName("alicepack_bottle_left")
group:getOrCreateLocation("ALICEpack Mag"):setAttachmentName("alicepack_mag")
group:getOrCreateLocation("ALICEpack Mag Right"):setAttachmentName("alicepack_mag_right")
group:getOrCreateLocation("ALICEpack Mag Left"):setAttachmentName("alicepack_mag_left")