TweakItem("Base.Golfclub", "AttachmentType", "BigBonk")
TweakItem("Base.Crowbar", "AttachmentType", "BigBonk")
TweakItem("Base.GardenHoe", "AttachmentType", "BigBonk")
TweakItem("Base.Poolcue", "AttachmentType", "BigBonk")
TweakItem("Base.PickAxe", "AttachmentType", "BigBonk")
TweakItem("Base.WoodAxe", "AttachmentType", "BigBonk")
TweakItem("Base.Sledgehammer", "AttachmentType", "BigBonk")
TweakItem("Base.Sledgehammer2", "AttachmentType", "BigBonk")
