require 'Items/ProceduralDistributions'
-- Autotsar.ATAJeepBumper3Item
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAJeepBumper3Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAJeepBumper3Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAJeepBumper3Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].junk.items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].junk.items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.1);
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 1);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 1);
table.insert(ProceduralDistributions.list["JanitorMisc"].items, "Autotsar.AtTuningMagJeep");
table.insert(ProceduralDistributions.list["JanitorMisc"].items, 1);

-- Base.ATAJeepInteractiveTrunkRoofRackItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAJeepInteractiveTrunkRoofRackItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAJeepInteractiveTrunkRoofRackItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATAJeepInteractiveTrunkRoofRackItem");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAJeepInteractiveTrunkRoofRackItem");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Autotsar.ATAJeepInteractiveTrunkRoofRackItem");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);
-- Base.ATAJeepInteractiveTrunkWheelRackItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAJeepInteractiveTrunkWheelRackItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAJeepInteractiveTrunkWheelRackItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATAJeepInteractiveTrunkWheelRackItem");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAJeepInteractiveTrunkWheelRackItem");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Autotsar.ATAJeepInteractiveTrunkWheelRackItem");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);
-- Base.ATAJeepRoofBaseItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAJeepRoofBaseItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAJeepRoofBaseItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATAJeepRoofBaseItem");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAJeepRoofBaseItem");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Autotsar.ATAJeepRoofBaseItem");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);

-- Base.ATAJeepRoofTentItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAJeepRoofTentItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAJeepRoofTentItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Autotsar.ATAJeepRoofTentItem");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Autotsar.ATAJeepRoofTentItem");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAJeepRoofTentItem");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 1);
-- Base.ATAJeepSnorkelItem
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfElectric"].items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["MechanicShelfElectric"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfElectric"].junk.items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["MechanicShelfElectric"].junk.items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Autotsar.ATAJeepSnorkelItem");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);