-- require "Items/Distributions"
-- require "Items/ProceduralDistributions"
-- -- table.insert(ProceduralDistributions.list.BedroomSideTable.items, "smallback")
-- -- table.insert(ProceduralDistributions.list.BedroomSideTable.items, 0.8)
-- table.insert(ProceduralDistributions.list.BedroomSideTable.items, "medbag")
-- table.insert(ProceduralDistributions.list.BedroomSideTable.items, 0.8)
-- table.insert(ProceduralDistributions.list.BedroomSideTable.items, "Leggings_Bottoms")
-- table.insert(ProceduralDistributions.list.BedroomSideTable.items, 1.5)


-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, "FlatCap")
-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, 1.5)
-- -- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, "Gloves_Rogue")
-- -- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, "strapchest_Military")
-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, 0.5)	
-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, "WetSuit")
-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, "HATELA")
-- table.insert(ProceduralDistributions.list.ArmyHangarOutfit.items, 0.3)

-- table.insert(ProceduralDistributions.list.ArmyStorageElectronics.items, "HATELA")
-- table.insert(ProceduralDistributions.list.ArmyStorageElectronics.items, 0.3)

-- table.insert(ProceduralDistributions.list.ArmyStorageGuns.items, "HolsterPLL2M")
-- table.insert(ProceduralDistributions.list.ArmyStorageGuns.items, 6)

-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "Gloves_Rogue")
-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "FlatCap")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 1.5)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "HolsterPLL2M")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 4)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "medbag")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.6)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "medbag2")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.6)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "MVest_Military")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.5)
-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "RogueWaistBag_Military")
-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.4)
-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "Shoes_Rogue")
-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.5)
-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "smallback")
-- -- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.8)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "strapchest_Military")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "TacticalWaistBagBack_Military")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.4)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "TacticalWaistBagBackMed")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.4)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "Vest_RogueVest_Military")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "Vest_WitchyCarrier_Military")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "WetSuit")
-- table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.5)	
	
-- -- table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, "smallback")
-- -- table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, 0.8)	

-- if ProceduralDistributions.list.ArmySurplusFootwear then
	-- -- table.insert(ProceduralDistributions.list.ArmySurplusFootwear.items, "Shoes_Rogue")
	-- -- table.insert(ProceduralDistributions.list.ArmySurplusFootwear.items, 0.5)	
-- end

-- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, "Hat_Altyn")
-- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, 0.6)	
-- -- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, "ClericNeck")
-- -- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, 0.5)	
-- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, "RogueMask")
-- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, 0.5)	
-- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, "FlatCap")
-- table.insert(ProceduralDistributions.list.ArmySurplusHeadwear.items, 1.5)	

-- if ProceduralDistributions.list.ArmySurplusMisc then

	-- -- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "RogueWaistBag")
	-- -- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.5)
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "TacticalWaistBagBack")
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.4)
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "TacticalWaistBagBackMed")
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.4)	
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "medbag")
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.6)		
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "medbag2")
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.6)	


	-- -- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "BeltRig")
	-- -- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.7)
	-- -- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "Gloves_Rogue")
	-- -- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.5)	
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "HolsterPLL2")
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 2)
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "HolsterPLL2M")
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 2)		
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, "strapchest")
	-- table.insert(ProceduralDistributions.list.ArmySurplusMisc.items, 0.5)	
-- end

-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, "ClericPants")
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, 0.5)	
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, "MVest")
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, 0.5)	
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, "Vest_RogueVest")
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, 0.5)	
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, "Vest_WitchyCarrier")
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, 0.6)	
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, "WetSuit")
-- table.insert(ProceduralDistributions.list.ArmySurplusOutfit.items, 0.5)	

-- -- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "BeltRig")
-- -- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.7)
-- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "medbag2")
-- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.5)
-- -- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "smallback")
-- -- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 1.5)
-- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "TacticalWaistBagBackMed")
-- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.3)
-- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "TacticalWaistBagBack")
-- table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.3)

-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, "WetSuit")
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, 0.5)
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, "PFVest")
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, 0.5)
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, "CropTop")
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, 0.5)
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, "PFCropped")
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, 0.5)
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, "PFShorts")
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, 0.5)
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, "PFPants")
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, 0.5)
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, "ShorterDenim")
-- table.insert(ProceduralDistributions.list.CampingStoreClothes.items, 0.4)



-- table.insert(ProceduralDistributions.list.ClothingStoresShoes.items, "Shoes_CanvasshoesLong")
-- table.insert(ProceduralDistributions.list.ClothingStoresShoes.items, 2)
-- table.insert(ProceduralDistributions.list.ClothingStoresShoes.items, "Shoes_Canvasshoes")
-- table.insert(ProceduralDistributions.list.ClothingStoresShoes.items, 3)

-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "ElbowbandL")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 1)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "ElbowbandR")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 1)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "WetSuit")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 0.5)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "PFVest")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 0.5)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "SportTankTop")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 0.5)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "PFCropped")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 0.5)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "PFShorts")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 0.5)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "PFKnee")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 0.5)
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, "PFPants")
-- table.insert(ProceduralDistributions.list.ClothingStoresSport.items, 0.5)




-- table.insert(ProceduralDistributions.list.ClothingStoresWoman.items, "CropTop")
-- table.insert(ProceduralDistributions.list.ClothingStoresWoman.items, 0.5)
-- table.insert(ProceduralDistributions.list.ClothingStoresWoman.items, "ShorterDenim")
-- table.insert(ProceduralDistributions.list.ClothingStoresWoman.items, 0.4)
-- table.insert(ProceduralDistributions.list.ClothingStoresWoman.items, "Leggings_Bottoms")
-- table.insert(ProceduralDistributions.list.ClothingStoresWoman.items, 3)




-- if ProceduralDistributions.list.CrateCamping then
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, "WetSuit")
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, 0.5)
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, "PFVest")
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, 0.5)
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, "CropTop")
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, 0.5)
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, "PFCropped")
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, 0.5)
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, "PFShorts")
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, 0.5)
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, "PFPants")
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, 0.5)
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, "ShorterDenim")
	-- table.insert(ProceduralDistributions.list.CrateCamping.items, 0.4)
-- end



-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "Vest_WitchyCarrier")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.5)
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "RogueMask")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.5)
-- -- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "RogueWaistBag")
-- -- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.5)
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "TacticalWaistBagBack")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.4)
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "strapchest")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.5)
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "MVest")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.3)
-- -- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "Shoes_Rogue")
-- -- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.2)
-- -- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "Gloves_Rogue")
-- -- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.3)
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "medbag2")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.2)
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "HolsterPLL2")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.5)	
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, "HolsterPLL2M")
-- table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.5)	

-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "strapchest_Military")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.5)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "MVest_Military")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.5)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "TacticalWaistBagBack_Military")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.4)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "TacticalWaistBagBackMed")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.4)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "HolsterPLL2M")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 4)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "medbag")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.6)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "medbag2")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.6)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "FlatCap")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 1.5)
-- -- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "smallback")
-- -- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.8)
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "HATELA")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.3)	
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "Vest_RogueVest_Military")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.5)	
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "Vest_WitchyCarrier_Military")
-- table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.5)	

-- table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "medbag")
-- table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 0.4)
-- table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "Bag_ParaMedic")
-- table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 0.5)

-- table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "TacticalWaistBagBackMed")
-- table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 0.3)
-- table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "Bag_ParaMedic")
-- table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 0.6)



-- table.insert(ProceduralDistributions.list.OptometristGlasses.items, "GlassesPLL")
-- table.insert(ProceduralDistributions.list.OptometristGlasses.items, 3)
-- table.insert(ProceduralDistributions.list.OptometristGlasses.items, "GlassesPLLR")
-- table.insert(ProceduralDistributions.list.OptometristGlasses.items, 3)


-- if ProceduralDistributions.list.PoliceDesk then
	-- table.insert(ProceduralDistributions.list.PoliceDesk.items, "HolsterPLL2")
	-- table.insert(ProceduralDistributions.list.PoliceDesk.items, 2)
-- end

-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "Vest_WitchyCarrier_Black")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 0.8)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "Vest_RogueVest_Black")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 0.8)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "HolsterPLL2")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 2)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "BeltRig")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 2)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "TacticalWaistBagBack_Black")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 0.5)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "HATELA")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 0.2)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "medbag2")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 0.7)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "strapchest_Black")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 0.5)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "FlatCap")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 1)
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, "MVest_Black")
-- table.insert(ProceduralDistributions.list.PoliceLockers.items, 0.5)

-- table.insert(ProceduralDistributions.list.PoliceStorageGuns.items, "HolsterPLL2")
-- table.insert(ProceduralDistributions.list.PoliceStorageGuns.items, 4)

-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "Vest_WitchyCarrier_Black")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.8)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "Vest_RogueVest_Black")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.8)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "Hat_Altyn")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.6)
-- -- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "HolsterPLL2")
-- -- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 3)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "BeltRig")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 2)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "TacticalWaistBagBack_Black")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "ClericPants")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "HATELA")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.2)
-- -- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "ClericNeck")
-- -- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "medbag2")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 1)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "strapchest_Black")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "MVest_Black ")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.5)
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "HATELA")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.3)

-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "Vest_WitchyCarrier_Black")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 0.1)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "Vest_RogueVest_Black")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 0.1)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "HolsterPLL2")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 2)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "BeltRig")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 2)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "TacticalWaistBagBack_Black")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 0.5)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "HATELA")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 0.2)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "medbag2")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 0.7)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "strapchest_Black")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 0.5)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "FlatCap")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 1)
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, "MVest_Black")
-- table.insert(ProceduralDistributions.list.PrisonGuardLockers.items, 0.5)

-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairP")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairPiggy")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairModern")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairWide")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairWendy")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairBun2")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairCroft")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairFio")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Hat_HairMarcel")
-- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 2)
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Animask1")
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 1)
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Animask2")
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 0.5)
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Animask12")
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 1)
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, "Animask22")
-- -- table.insert(ProceduralDistributions.list.SalonShelfHaircare.items, 0.5)

-- if ProceduralDistributions.list.SecurityLockers then
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, "BeltRig")
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, 0.2)
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, "HolsterPLL2")
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, 2)
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, "TacticalWaistBagBack_Black")
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, 0.2)
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, "HATELA")
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, 0.3)
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, "Vest_WitchyCarrier_Black")
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, 0.2)
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items,  "Vest_RogueVest_Black")
	-- table.insert(ProceduralDistributions.list.SecurityLockers.items, 0.2)
-- end


-- if ProceduralDistributions.list.StripClubDressers then
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairP")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairPiggy")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairModern")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairWide")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairWendy")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairBun2")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairCroft")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairFio")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, "Hat_HairMarcel")
	-- table.insert(ProceduralDistributions.list.StripClubDressers.junk.items, 2)
-- end

-- table.insert(ProceduralDistributions.list.WardrobeMan.items, "medbag")
-- table.insert(ProceduralDistributions.list.WardrobeMan.items, 0.8)

-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "medbag")
-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.8)

-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "medbag")
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.8)
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "Vest_WitchyCarrier")
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.2)
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items,  "Vest_RogueVest")
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.2)

-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, "medbag")
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, 0.8)
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, "Leggings_Bottoms")
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, 1.5)

-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "medbag")
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.8)
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "Leggings_Bottoms")
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 1.5)