require "Items/Distributions"
require "Items/ItemPicker"

if ProceduralDistributions.list.ArmySurplusBackpacks then	
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, "Bag_ALICEpack_Army_WithAttachment")
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, 0.1)
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, "Bag_ALICEpack_Army_With2Attachments")
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, 0.01)
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, "Bag_ALICEpack_Army_With3Attachments")
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, 0.001)
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, "Bag_NormalHikingBag_WithAttachment")
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, 0.1)	
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, "Bag_BigHikingBag_WithAttachment")
	table.insert(ProceduralDistributions.list.ArmySurplusBackpacks.items, 0.1)
end

if ProceduralDistributions.list.CampingStoreBackpacks then	
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "Bag_ALICEpack_Army_WithAttachment")
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.1)
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "Bag_ALICEpack_Army_With2Attachments")
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.01)
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "Bag_ALICEpack_Army_With3Attachments")
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.001)
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "Bag_NormalHikingBag_WithAttachment")
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.1)	
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "Bag_BigHikingBag_WithAttachment")
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.1)
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, "Bag_Schoolbag_WithAttachment")
	table.insert(ProceduralDistributions.list.CampingStoreBackpacks.items, 0.1)	
end

table.insert(ProceduralDistributions.list.FirearmWeapons.items, "Bag_ALICEpack_Army_WithAttachment")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 1)
table.insert(ProceduralDistributions.list.FirearmWeapons.items, "Bag_ALICEpack_Army_With2Attachments")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 1)
table.insert(ProceduralDistributions.list.FirearmWeapons.items, "Bag_ALICEpack_Army_With3Attachments")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 1)

-- table.insert(SuburbsDistributions.armystorage.locker.items, "Bag_ALICEpack_Army_WithAttachment")
-- table.insert(SuburbsDistributions.armystorage.locker.items, 0.1)
-- table.insert(SuburbsDistributions.armystorage.locker.items, "Bag_ALICEpack_Army_With2Attachments")
-- table.insert(SuburbsDistributions.armystorage.locker.items, 0.01)
-- table.insert(SuburbsDistributions.armystorage.locker.items, "Bag_ALICEpack_Army_With3Attachments")
-- table.insert(SuburbsDistributions.armystorage.locker.items, 0.001)	

table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "Bag_ALICEpack_Army_WithAttachment")
table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.1)
table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "Bag_ALICEpack_Army_With2Attachments")
table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.01)
table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, "Bag_ALICEpack_Army_With3Attachments")
table.insert(ProceduralDistributions.list.ArmyStorageOutfit.items, 0.001)


-- table.insert(SuburbsDistributions.policestorage.locker.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.policestorage.locker.items, 0.1)
		
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.PoliceStorageOutfit.items, 0.1)

-- table.insert(SuburbsDistributions.mechanic.wardrobe.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.mechanic.wardrobe.items, 0.1)

-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, 0.03)
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, 0.01)
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, 0.01)
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, 0.001)
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.motelroomoccupied.other.items, 0.001)

-- table.insert(SuburbsDistributions.laundry.counter.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.laundry.counter.items, 0.2)

-- table.insert(SuburbsDistributions.sportstore.shelves.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstore.shelves.items, 0.3)
-- table.insert(SuburbsDistributions.sportstore.shelves.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstore.shelves.items, 0.08)
-- table.insert(SuburbsDistributions.sportstore.shelves.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstore.shelves.items, 0.05)
-- table.insert(SuburbsDistributions.sportstore.shelves.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstore.shelves.items, 0.008)
-- table.insert(SuburbsDistributions.sportstore.shelves.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstore.shelves.items, 0.005)

-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, 0.3)
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, 0.08)
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, 0.05)
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, 0.008)
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstore.clothingrack.items, 0.005)

-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, 0.3)
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, 0.08)
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, 0.05)
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, 0.008)
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstorage.metal_shelves.items, 0.005)

-- table.insert(SuburbsDistributions.sportstorage.shelves.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, 0.3)
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, 0.08)
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, 0.05)
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, 0.008)
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstorage.shelves.items, 0.005)

-- table.insert(SuburbsDistributions.sportstorage.crate.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.crate.items, 0.3)
-- table.insert(SuburbsDistributions.sportstorage.crate.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.crate.items, 0.08)
-- table.insert(SuburbsDistributions.sportstorage.crate.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.sportstorage.crate.items, 0.05)
-- table.insert(SuburbsDistributions.sportstorage.crate.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstorage.crate.items, 0.008)
-- table.insert(SuburbsDistributions.sportstorage.crate.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.sportstorage.crate.items, 0.005)

-- table.insert(SuburbsDistributions.changeroom.locker.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.changeroom.locker.items, 0.3)
-- table.insert(SuburbsDistributions.changeroom.locker.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.changeroom.locker.items, 0.08)
-- table.insert(SuburbsDistributions.changeroom.locker.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(SuburbsDistributions.changeroom.locker.items, 0.05)
-- table.insert(SuburbsDistributions.changeroom.locker.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.changeroom.locker.items, 0.008)
-- table.insert(SuburbsDistributions.changeroom.locker.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(SuburbsDistributions.changeroom.locker.items, 0.005)

-- table.insert(SuburbsDistributions.camping.clothingrack.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(SuburbsDistributions.camping.clothingrack.items, 0.3)

table.insert(ProceduralDistributions.list.GigamartSchool.items, "Bag_Schoolbag_WithAttachment")
table.insert(ProceduralDistributions.list.GigamartSchool.items, 0.2)	

table.insert(ProceduralDistributions.list.WardrobeChild.items, "Bag_Schoolbag_WithAttachment")
table.insert(ProceduralDistributions.list.WardrobeChild.items, 0.05)	

-- table.insert(ProceduralDistributions.list.LockerClassy.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(ProceduralDistributions.list.LockerClassy.items, 0.1)
-- table.insert(ProceduralDistributions.list.LockerClassy.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.LockerClassy.items, 0.08)
-- table.insert(ProceduralDistributions.list.LockerClassy.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.LockerClassy.items, 0.05)	
-- table.insert(ProceduralDistributions.list.LockerClassy.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.LockerClassy.items, 0.008)
-- table.insert(ProceduralDistributions.list.LockerClassy.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.LockerClassy.items, 0.005)		

-- table.insert(ProceduralDistributions.list.Locker.items, "Bag_Schoolbag_WithAttachment")
-- table.insert(ProceduralDistributions.list.Locker.items, 0.2)
-- table.insert(ProceduralDistributions.list.Locker.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.Locker.items, 0.12)
-- table.insert(ProceduralDistributions.list.Locker.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.Locker.items, 0.1)	
-- table.insert(ProceduralDistributions.list.Locker.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.Locker.items, 0.012)
-- table.insert(ProceduralDistributions.list.Locker.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.Locker.items, 0.01)		

-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.08)	
-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.05)	

-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.08)	
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.06)	

-- table.insert(ProceduralDistributions.list.WardrobeMan.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeMan.items, 0.08)	
-- table.insert(ProceduralDistributions.list.WardrobeMan.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeMan.items, 0.05)	

-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, 0.08)	
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, "Bag_BigHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, 0.06)	

-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "Bag_NormalHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.08)	
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items,"Bag_BigHikingBag_WithAttachment")
-- table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.05)		

-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.008)	
-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.005)	

-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.008)	
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.006)	

-- table.insert(ProceduralDistributions.list.WardrobeMan.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeMan.items, 0.008)	
-- table.insert(ProceduralDistributions.list.WardrobeMan.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeMan.items, 0.005)	

-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, "Bag_NormalHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, 0.008)	
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, "Bag_BigHikingBag_With2Attachments")
-- table.insert(ProceduralDistributions.list.WardrobeWoman.items, 0.006)	

table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "Bag_NormalHikingBag_With2Attachments")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.008)	
table.insert(ProceduralDistributions.list.WardrobeRedneck.items,"Bag_BigHikingBag_With2Attachments")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.005)	




