require "Items/Distributions"
require "Items/ProceduralDistributions"
require "Vehicles/VehicleDistributions"

ISLiteratureUI.SetItemHidden("IntelFolder", true)
--PrisonCellRandom

table.insert(ProceduralDistributions.list.PrisonCellRandom.items, "IntelFolder")
table.insert(ProceduralDistributions.list.PrisonCellRandom.items, 0.1)
table.insert(ProceduralDistributions.list.PrisonCellRandom.items, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.PrisonCellRandom.items, 0.1)
table.insert(ProceduralDistributions.list.PrisonCellRandom.items, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.PrisonCellRandom.items, 0.01)
table.insert(ProceduralDistributions.list.PrisonCellRandom.items, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.PrisonCellRandom.items, 0.001)

table.insert(SuburbsDistributions.all.bin.items, "IntelFolder")
table.insert(SuburbsDistributions.all.bin.items, 0.0001)

table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "IntelFolder")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.1)
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "LabKeycard")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.01)
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.1)
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.01)
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.001)

table.insert(ProceduralDistributions.list.MeleeWeapons.items, "IntelFolder")
table.insert(ProceduralDistributions.list.MeleeWeapons.items, 0.1)
table.insert(ProceduralDistributions.list.MeleeWeapons.items, "LabKeycard")
table.insert(ProceduralDistributions.list.MeleeWeapons.items, 0.1)


table.insert(ProceduralDistributions.list.PlankStashGun.items, "IntelFolder")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 1)
table.insert(ProceduralDistributions.list.PlankStashGun.items, "LabKeycard")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 1)
table.insert(ProceduralDistributions.list.PlankStashGun.items, "BlackwebDiskette")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 1)
table.insert(ProceduralDistributions.list.PlankStashGun.items, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 1)
table.insert(ProceduralDistributions.list.PlankStashGun.items, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 0.1)
table.insert(ProceduralDistributions.list.PlankStashGun.items, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 0.01)

table.insert(SuburbsDistributions.Bag_MoneyBag.items, "IntelFolder")
table.insert(SuburbsDistributions.Bag_MoneyBag.items, 1)
table.insert(SuburbsDistributions.Bag_MoneyBag.items, "IntelFolder")
table.insert(SuburbsDistributions.Bag_MoneyBag.items, 1)
table.insert(SuburbsDistributions.Bag_MoneyBag.items, "LabKeycard")
table.insert(SuburbsDistributions.Bag_MoneyBag.items, 0.1)
table.insert(SuburbsDistributions.Bag_MoneyBag.items, "LabKeycard")
table.insert(SuburbsDistributions.Bag_MoneyBag.items, 0.1)
table.insert(SuburbsDistributions.Bag_MoneyBag.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.Bag_MoneyBag.items, 1)
table.insert(SuburbsDistributions.Bag_MoneyBag.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.Bag_MoneyBag.items, 0.1)
table.insert(SuburbsDistributions.Bag_MoneyBag.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.Bag_MoneyBag.items, 0.10)

table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, "IntelFolder")
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, 0.01)
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, 0.01)
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, "LabKeycard")
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, 0.001)
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, 0.01)
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, 0.001)
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.motelroomoccupied.dresser.items, 0.0001)

table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, "IntelFolder")
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, 0.01)
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, 0.01)
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, "LabKeycard")
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, 0.001)
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, 0.01)
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, 0.001)
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.motelroomoccupied.sidetable.items, 0.0001)

table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "IntelFolder")
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.01)
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "LabKeycard")
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.001)
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.01)
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.001)
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, 0.0001)

table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "IntelFolder")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.01)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "LabKeycard")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.001)
table.insert(ProceduralDistributions.list.WardrobeManClassy.items, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.01)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.001)
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.WardrobeWomanClassy.items, 0.0001)



table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, "IntelFolder")
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, 0.01)
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, "LabKeycard")
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, 0.001)
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, "BlackwebDiskette")
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, 0.001)
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, 0.01)
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, 0.001)
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.FilingCabinetGeneric.junk, 0.0001)


--FilingCabinetGeneric

table.insert(ProceduralDistributions.list.LockerClassy.items, "IntelFolder")
table.insert(ProceduralDistributions.list.LockerClassy.items, 0.01)
table.insert(ProceduralDistributions.list.LockerClassy.items,  "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.LockerClassy.items, 0.001)
table.insert(ProceduralDistributions.list.LockerClassy.items, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.LockerClassy.items, 0.01)
table.insert(ProceduralDistributions.list.LockerClassy.items, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.LockerClassy.items, 0.0001)

-- table.insert(ProceduralDistributions.list.Locker.junk, "IntelFolder")
-- table.insert(ProceduralDistributions.list.Locker.junk, 0.001)
-- table.insert(ProceduralDistributions.list.Locker.junk, "LabKeycard")
-- table.insert(ProceduralDistributions.list.Locker.junk, 0.0001)
-- table.insert(ProceduralDistributions.list.Locker.junk, "BlackwebDiskette")
-- table.insert(ProceduralDistributions.list.Locker.junk, 0.0001)

table.insert(ProceduralDistributions.list.DeskGeneric.junk, "IntelFolder")
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  0.01)
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  "LabKeycard")
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  0.001)
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  "BlackwebDiskette")
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  0.001)
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  0.001)
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  0.0001)
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.DeskGeneric.junk,  0.0001)




table.insert(ProceduralDistributions.list.OfficeCounter.junk, "IntelFolder")
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  0.1)
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  "LabKeycard")
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  "BlackwebDiskette")
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  0.0001)
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.OfficeCounter.junk,  0.0001)



table.insert(ProceduralDistributions.list.OfficeDesk.junk, "IntelFolder")
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  0.1)
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  "LabKeycard")
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  "BlackwebDiskette")
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDesk.junk, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  0.1)
table.insert(ProceduralDistributions.list.OfficeDesk.junk, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.OfficeDesk.junk,  0.0001)



table.insert(ProceduralDistributions.list.OfficeDrawers.junk, "IntelFolder")
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  0.1)
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  "LabKeycard")
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  "BlackwebDiskette")
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDrawers.junk, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  0.1)
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.OfficeDrawers.junk,  0.0001)


table.insert(ProceduralDistributions.list.OfficeDeskHome.junk, "IntelFolder")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  0.1)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  "LabKeycard")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  "BlackwebDiskette")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  0.01)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  0.1)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  0.001)
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.OfficeDeskHome.junk,  0.0001)


table.insert(ProceduralDistributions.list.PoliceDesk.junk, "IntelFolder")
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  0.1)
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  "LabKeycard")
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  0.001)
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  "BlackwebDiskette")
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  0.001)
table.insert(ProceduralDistributions.list.PoliceDesk.junk, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  0.1)
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  0.001)
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.PoliceDesk.junk,  0.0001)


table.insert(ProceduralDistributions.list.FirearmWeapons.items, "IntelFolder")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 0.1)
table.insert(ProceduralDistributions.list.FirearmWeapons.items, "LabKeycard")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 0.1)
table.insert(ProceduralDistributions.list.FirearmWeapons.items, "BlackwebDiskette")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 0.1)

table.insert(ProceduralDistributions.list.FirearmWeapons.items, "MHLSealedDocumentConfidential")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 0.1)
table.insert(ProceduralDistributions.list.FirearmWeapons.items, "MHLSealedDocumentSecret")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 0.1)
table.insert(ProceduralDistributions.list.FirearmWeapons.items, "MHLSealedDocumentTopSecret")
table.insert(ProceduralDistributions.list.FirearmWeapons.items, 0.1)



-- table.insert(SuburbsDistributions.all.filingcabinet.junk, "IntelFolder")
-- table.insert(SuburbsDistributions.all.filingcabinet.junk, 0.01)
-- table.insert(SuburbsDistributions.all.filingcabinet.junk, "LabKeycard")
-- table.insert(SuburbsDistributions.all.filingcabinet.junk, 0.001)
-- table.insert(SuburbsDistributions.all.filingcabinet.junk, "BlackwebDiskette")
-- table.insert(SuburbsDistributions.all.filingcabinet.junk, 0.001)



table.insert(SuburbsDistributions.Briefcase.items, "IntelFolder")
table.insert(SuburbsDistributions.Briefcase.items, 0.1)
table.insert(SuburbsDistributions.Briefcase.items, "LabKeycard")
table.insert(SuburbsDistributions.Briefcase.items, 0.01)
table.insert(SuburbsDistributions.Briefcase.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.Briefcase.items, 0.01)
table.insert(SuburbsDistributions.Briefcase.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.Briefcase.items, 0.1)
table.insert(SuburbsDistributions.Briefcase.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.Briefcase.items, 0.01)
table.insert(SuburbsDistributions.Briefcase.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.Briefcase.items, 0.001)

table.insert(SuburbsDistributions.Handbag.items, "IntelFolder")
table.insert(SuburbsDistributions.Handbag.items, 0.01)
table.insert(SuburbsDistributions.Handbag.items, "LabKeycard")
table.insert(SuburbsDistributions.Handbag.items, 0.001)
table.insert(SuburbsDistributions.Handbag.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.Handbag.items, 0.001)

table.insert(SuburbsDistributions.Purse.items, "IntelFolder")
table.insert(SuburbsDistributions.Purse.items, 0.01)
table.insert(SuburbsDistributions.Purse.items, "LabKeycard")
table.insert(SuburbsDistributions.Purse.items, 0.001)
table.insert(SuburbsDistributions.Purse.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.Purse.items, 0.001)

table.insert(SuburbsDistributions.Suitcase.items, "IntelFolder")
table.insert(SuburbsDistributions.Suitcase.items, 0.01)
table.insert(SuburbsDistributions.Suitcase.items, "LabKeycard")
table.insert(SuburbsDistributions.Suitcase.items, 0.001)
table.insert(SuburbsDistributions.Suitcase.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.Suitcase.items, 0.001)
table.insert(SuburbsDistributions.Suitcase.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.Suitcase.items, 0.01)
table.insert(SuburbsDistributions.Suitcase.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.Suitcase.items, 0.001)
table.insert(SuburbsDistributions.Suitcase.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.Suitcase.items, 0.0001)


table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, "IntelFolder")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, "LabKeycard")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items,  "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.1)

table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, "IntelFolder")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, "LabKeycard")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.1)
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.1)
	
-- table.insert(SuburbsDistributions.policestorage.locker.items, "IntelFolder")
-- table.insert(SuburbsDistributions.policestorage.locker.items, 0.1)	
-- table.insert(SuburbsDistributions.policestorage.locker.items, "LabKeycard")
-- table.insert(SuburbsDistributions.policestorage.locker.items, 0.01)		
-- table.insert(SuburbsDistributions.policestorage.locker.items, "BlackwebDiskette")
-- table.insert(SuburbsDistributions.policestorage.locker.items, 0.01)	

-- table.insert(SuburbsDistributions.security.locker.items, "IntelFolder")
-- table.insert(SuburbsDistributions.security.locker.items, 0.1)	
-- table.insert(SuburbsDistributions.security.locker.items, "LabKeycard")
-- table.insert(SuburbsDistributions.security.locker.items, 0.01)
	
-- table.insert(SuburbsDistributions.armystorage.locker.items, "IntelFolder")
-- table.insert(SuburbsDistributions.armystorage.locker.items, 0.1)	
-- table.insert(SuburbsDistributions.armystorage.locker.items, "LabKeycard")
-- table.insert(SuburbsDistributions.armystorage.locker.items, 0.01)

table.insert(SuburbsDistributions.Bag_WeaponBag.items, "IntelFolder")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.1)	
table.insert(SuburbsDistributions.Bag_WeaponBag.items, "LabKeycard")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.01)	
table.insert(SuburbsDistributions.Bag_WeaponBag.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.01)	
table.insert(SuburbsDistributions.Bag_WeaponBag.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.1)	
table.insert(SuburbsDistributions.Bag_WeaponBag.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.01)	
table.insert(SuburbsDistributions.Bag_WeaponBag.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.01)

table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, "IntelFolder")
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, 0.1)
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, "LabKeycard")
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, 0.01)
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, 0.1)
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, 0.01)
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.Bag_ALICEpack_Army.items, 0.001)

table.insert(SuburbsDistributions.Bag_ALICEpack.items, "IntelFolder")
table.insert(SuburbsDistributions.Bag_ALICEpack.items, 0.1)
table.insert(SuburbsDistributions.Bag_ALICEpack.items, "LabKeycard")
table.insert(SuburbsDistributions.Bag_ALICEpack.items, 0.1)	
table.insert(SuburbsDistributions.Bag_ALICEpack.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.Bag_ALICEpack.items, 0.1)	
	
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, "IntelFolder")
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, 0.1)	
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, "LabKeycard")
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, 0.1)
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, "BlackwebDiskette")
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, 0.1)


table.insert(VehicleDistributions.GloveBox.junk, "IntelFolder")
table.insert(VehicleDistributions.GloveBox.junk, 0.01)	
table.insert(VehicleDistributions.GloveBox.junk, "LabKeycard")
table.insert(VehicleDistributions.GloveBox.junk, 0.001)	
table.insert(VehicleDistributions.GloveBox.junk, "BlackwebDiskette")
table.insert(VehicleDistributions.GloveBox.junk, 0.001)	
table.insert(VehicleDistributions.GloveBox.junk, "MHLSealedDocumentConfidential")
table.insert(VehicleDistributions.GloveBox.junk, 0.01)	
table.insert(VehicleDistributions.GloveBox.junk, "MHLSealedDocumentSecret")
table.insert(VehicleDistributions.GloveBox.junk, 0.001)	
table.insert(VehicleDistributions.GloveBox.junk, "MHLSealedDocumentTopSecret")
table.insert(VehicleDistributions.GloveBox.junk, 0.0001)	

table.insert(VehicleDistributions.Seat.junk, "IntelFolder")
table.insert(VehicleDistributions.Seat.junk, 0.001)	
table.insert(VehicleDistributions.Seat.junk, "LabKeycard")
table.insert(VehicleDistributions.Seat.junk, 0.0001)	
table.insert(VehicleDistributions.Seat.junk, "BlackwebDiskette")
table.insert(VehicleDistributions.Seat.junk, 0.0001)	
table.insert(VehicleDistributions.Seat.junk, "MHLSealedDocumentConfidential")
table.insert(VehicleDistributions.Seat.junk, 0.001)	
table.insert(VehicleDistributions.Seat.junk, "MHLSealedDocumentSecret")
table.insert(VehicleDistributions.Seat.junk, 0.0001)	
table.insert(VehicleDistributions.Seat.junk, "MHLSealedDocumentTopSecret")
table.insert(VehicleDistributions.Seat.junk, 0.00001)	


table.insert(VehicleDistributions.Police.GloveBox.junk, "IntelFolder")
table.insert(VehicleDistributions.Police.GloveBox.junk, 0.1)	
table.insert(VehicleDistributions.Police.GloveBox.junk, "LabKeycard")
table.insert(VehicleDistributions.Police.GloveBox.junk, 0.01)	
table.insert(VehicleDistributions.Police.GloveBox.junk, "BlackwebDiskette")
table.insert(VehicleDistributions.Police.GloveBox.junk, 0.001)	
table.insert(VehicleDistributions.Police.GloveBox.junk, "MHLSealedDocumentConfidential")
table.insert(VehicleDistributions.Police.GloveBox.junk, 0.1)	
table.insert(VehicleDistributions.Police.GloveBox.junk, "MHLSealedDocumentSecret")
table.insert(VehicleDistributions.Police.GloveBox.junk, 0.01)	
table.insert(VehicleDistributions.Police.GloveBox.junk, "MHLSealedDocumentTopSecret")
table.insert(VehicleDistributions.Police.GloveBox.junk, 0.001)	

table.insert(VehicleDistributions.SurvivalistTruckBed.items, "IntelFolder")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 1)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "LabKeycard")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 1)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "BlackwebDiskette")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 1)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "MHLSealedDocumentConfidential")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 1)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "MHLSealedDocumentSecret")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 1)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "MHLSealedDocumentTopSecret")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 1)
	
table.insert(VehicleDistributions.Radio.TruckBed.items, "IntelFolder")
table.insert(VehicleDistributions.Radio.TruckBed.items, 5)		
table.insert(VehicleDistributions.Radio.TruckBed.items, "BlackwebDiskette")
table.insert(VehicleDistributions.Radio.TruckBed.items, 0.1)	
table.insert(VehicleDistributions.Radio.TruckBed.items,  "MHLSealedDocumentConfidential")
table.insert(VehicleDistributions.Radio.TruckBed.items, 0.1)			
table.insert(VehicleDistributions.Radio.TruckBed.items, "MHLSealedDocumentSecret")
table.insert(VehicleDistributions.Radio.TruckBed.items, 0.01)		
table.insert(VehicleDistributions.Radio.TruckBed.items, "MHLSealedDocumentTopSecret")
table.insert(VehicleDistributions.Radio.TruckBed.items, 0.001)	

if VehicleDistributions.Military then
	table.insert(VehicleDistributions.MilitarySeat.items, "IntelFolder")
	table.insert(VehicleDistributions.MilitarySeat.items, 0.1)	
	table.insert(VehicleDistributions.MilitarySeat.items, "LabKeycard")
	table.insert(VehicleDistributions.MilitarySeat.items, 0.1)
	table.insert(VehicleDistributions.MilitarySeat.items, "BlackwebDiskette")
	table.insert(VehicleDistributions.MilitarySeat.items, 0.1)
	table.insert(VehicleDistributions.MilitarySeat.items, "MHLSealedDocumentConfidential")
	table.insert(VehicleDistributions.MilitarySeat.items, 0.1)	
	table.insert(VehicleDistributions.MilitarySeat.items, "MHLSealedDocumentSecret")
	table.insert(VehicleDistributions.MilitarySeat.items, 0.1)
	table.insert(VehicleDistributions.MilitarySeat.items, "MHLSealedDocumentTopSecret")
	table.insert(VehicleDistributions.MilitarySeat.items, 0.1)
end


if VehicleDistributions.blackoppsSeat then
	table.insert(VehicleDistributions.blackoppsSeat.items, "IntelFolder")
	table.insert(VehicleDistributions.blackoppsSeat.items, 1)	
	table.insert(VehicleDistributions.blackoppsSeat.items, "LabKeycard")
	table.insert(VehicleDistributions.blackoppsSeat.items, 1)
	table.insert(VehicleDistributions.blackoppsSeat.items, "BlackwebDiskette")
	table.insert(VehicleDistributions.blackoppsSeat.items, 1)
	table.insert(VehicleDistributions.blackoppsSeat.items, "MHLSealedDocumentConfidential")
	table.insert(VehicleDistributions.blackoppsSeat.items, 1)	
	table.insert(VehicleDistributions.blackoppsSeat.items, "MHLSealedDocumentSecret")
	table.insert(VehicleDistributions.blackoppsSeat.items, 1)
	table.insert(VehicleDistributions.blackoppsSeat.items, "MHLSealedDocumentTopSecret")
	table.insert(VehicleDistributions.blackoppsSeat.items, 1)
	--blackoppsTrunk
	--blackoppsGloveBox
	
end


SuburbsDistributions.all.Outfit_ArmyCamoDesert = SuburbsDistributions.all.Outfit_ArmyCamoDesert or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoDesert.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoDesert.items, 0.01)        
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoDesert.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoDesert.items, 0.001)

SuburbsDistributions.all.Outfit_ArmyCamoGreen = SuburbsDistributions.all.Outfit_ArmyCamoGreen or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoGreen.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoGreen.items, 0.01)        
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoGreen.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_ArmyCamoGreen.items, 0.001)

SuburbsDistributions.all.Outfit_ArmyInstructor = SuburbsDistributions.all.Outfit_ArmyInstructor or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_ArmyInstructor.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_ArmyInstructor.items, 0.1)        
table.insert(SuburbsDistributions.all.Outfit_ArmyInstructor.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_ArmyInstructor.items, 0.01) 

SuburbsDistributions.all.Outfit_ArmyServiceUniform = SuburbsDistributions.all.Outfit_ArmyServiceUniform or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, 0.1)        
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, 0.1)
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items,  "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, 0.1)        
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, 0.1)       
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.all.Outfit_ArmyServiceUniform.items, 0.1)

SuburbsDistributions.all.Outfit_HazardSuit = SuburbsDistributions.all.Outfit_HazardSuit or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, 0.1)        
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, 0.1)      
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, 0.1)         
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, 0.1)         
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.all.Outfit_HazardSuit.items, 0.1)       

SuburbsDistributions.all.Outfit_Security = SuburbsDistributions.all.Outfit_Security or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_Security.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_Security.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Security.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_Security.items, 0.01)
table.insert(SuburbsDistributions.all.Outfit_Security.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.all.Outfit_Security.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Security.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.all.Outfit_Security.items, 0.01)   
table.insert(SuburbsDistributions.all.Outfit_Security.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.all.Outfit_Security.items, 0.001)


SuburbsDistributions.all.Outfit_Survivalist = SuburbsDistributions.all.Outfit_Survivalist or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, 0.01)
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, 0.01)  
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.all.Outfit_Survivalist.items, 0.001)

SuburbsDistributions.all.Outfit_Survivalist02 = SuburbsDistributions.all.Outfit_Survivalist02 or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, 0.10)
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, 0.01)  
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.all.Outfit_Survivalist02.items, 0.001)

SuburbsDistributions.all.Outfit_Survivalist03 = SuburbsDistributions.all.Outfit_Survivalist03 or {rolls = 1,items = {},junk= {rolls =1, items={}}}
        
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, "IntelFolder")
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, "LabKeycard")
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, 0.01)
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, "MHLSealedDocumentConfidential")
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, 0.1)     
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, "MHLSealedDocumentSecret")
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, 0.01)  
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, "MHLSealedDocumentTopSecret")
table.insert(SuburbsDistributions.all.Outfit_Survivalist03.items, 0.001)