Distributions = Distributions or {};

local distributionTable = 
{

	smallback = {	-- adventurers bag, surplus, sports
		rolls = 1,
		items = {
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
		}
		},

	
	TacticalWaistBagBack = {	-- adventurers bag, surplus, sports
		rolls = 1,
		items = {
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
		}
		},
	RogueWaistBag = {	-- adventurers bag, surplus, sports
		rolls = 1,
		items = {
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
		}
		},
	
	

	
	medbag2 = { -- stores
		rolls = 1,
		items = {
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
		}
		},
	
	
	
	
	
	BeltRig = { -- police storage
		rolls = 1,
		items = {
                               "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
		}
		},
	
	
	MVest = { -- stores
		rolls = 1,
		items = {
                               "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "MRE", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
		}
		},
	
	
	SWATPouch = { -- stores
		rolls = 1,
		items = {
                "Bandaid", 1,
                "SutureNeedle", 1,
                "Bandage", 1,
                "AlcoholWipes", 1,
                "9mmClip", 2,
                "45Clip", 2,
                "44Clip", 2,
                "M14Clip", 2,
                "556Clip", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"Bullets9mm",5,
				"Bullets45",5,
				"Bullets44",5,
				"Bullets38",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"556Bullets",5,
                "9mmClip", 2,
                "45Clip", 2,
                "44Clip", 2,
                "M14Clip", 2,
                "556Clip", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"Bullets9mm",5,
				"Bullets45",5,
				"Bullets44",5,
				"Bullets38",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"556Bullets",5,
				
				"HandTorch",1,
                "Screwdriver", 4,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"Lighter",1,
				"Matches",1,
				"Cigarettes",1,
		}
		},
	
	Bag_BigSwatBag = { -- stores
		rolls = 1,
		items = {
                "Bandaid", 1,
                "SutureNeedle", 1,
                "Bandage", 1,
                "AlcoholWipes", 1,
                "MRE", 2,
                "MRE", 2,
                "HolsterSimple", 3,
                "HolsterDouble", 0.8,
                "Nightstick", 4,
                "Bullets9mmBox", 3,
                "ShotgunShellsBox", 3,
                "Bullets38Box", 3,
                "Bullets44Box", 3,
                "Bullets45Box", 3,
                "223Box", 3,
                "308Box", 3,
                "Bullets9mmBox", 3,
                "ShotgunShellsBox", 3,
                "Bullets38Box", 3,
                "Bullets44Box", 3,
                "Bullets45Box", 3,
                "223Box", 3,
                "308Box", 3,
                "PistolCase1", 1.5,
                "PistolCase2", 1.5,
                "PistolCase3", 0.5,
                "Revolver", 1,
                "Revolver_Long", 0.5,
                "Radio.WalkieTalkie4",10,
                "Radio.WalkieTalkie5",2,
                "9mmClip", 2,
                "45Clip", 2,
                "44Clip", 2,
                "M14Clip", 2,
                "556Clip", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "45Clip", 2,
                "44Clip", 2,
                "M14Clip", 2,
                "556Clip", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
				"Bullets9mm",5,
				"Bullets45",5,
				"Bullets44",5,
				"Bullets38",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"556Bullets",5,
				"Bullets9mm",5,
				"Bullets45",5,
				"Bullets44",5,
				"Bullets38",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"556Bullets",5,
				"Glasses_SwatGoggles",0.5,
				"Gloves_SwatGloves", 0.5,
				"SwatElbowPads",0.5,
				"SwatKneePads", 0.5,
				"Gloves_RiotGloves", 0.5,
                "HandTorch", 3,
				"Hat_GasMask",1,
				"Hat_NBCmask",0.1,
				"RogueMask", 0.1,
                "Mask_HECU", 0.1,
				"Hat_SwatGasMask", 0.1,
		}
		},
	
	Bag_PoliceBag = { -- stores
		rolls = 1,
		items = {
                "Bandaid", 1,
                "SutureNeedle", 1,
                "Bandage", 1,
                "AlcoholWipes", 1,
                "MRE", 2,
                "MRE", 2,
                "HolsterSimple", 3,
                "HolsterDouble", 0.8,
                "Nightstick", 4,
                "Bullets9mmBox", 3,
                "ShotgunShellsBox", 3,
                "Bullets38Box", 3,
                "Bullets44Box", 3,
                "Bullets45Box", 3,
                "223Box", 3,
                "308Box", 3,
                "Bullets9mmBox", 3,
                "ShotgunShellsBox", 3,
                "Bullets38Box", 3,
                "Bullets44Box", 3,
                "Bullets45Box", 3,
                "223Box", 3,
                "308Box", 3,
                "PistolCase1", 1.5,
                "PistolCase2", 1.5,
                "PistolCase3", 0.5,
                "Revolver", 1,
                "Revolver_Long", 0.5,
                "Radio.WalkieTalkie4",10,
                "Radio.WalkieTalkie5",2,
                "9mmClip", 2,
                "45Clip", 2,
                "44Clip", 2,
                "M14Clip", 2,
                "556Clip", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
                "45Clip", 2,
                "44Clip", 2,
                "M14Clip", 2,
                "556Clip", 2,
				"ConcussionGrenade",1,
				"SmokeGrenade",1,
				"BrushKit",1,
				"MainKit",1,
				"Knuckleduster",1,
				"Leatherdad",1,
				"SAK",1,
				"Flashlight_Military",1,
				"Canteen",1,
				"Canteenfull",1,
				"P38DT", 1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
				"Bullets9mm",5,
				"Bullets45",5,
				"Bullets44",5,
				"Bullets38",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"556Bullets",5,
				"Bullets9mm",5,
				"Bullets45",5,
				"Bullets44",5,
				"Bullets38",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"556Bullets",5,
				"Glasses_SwatGoggles",0.5,
				"Gloves_SwatGloves", 0.5,
				"SwatElbowPads",0.5,
				"SwatKneePads", 0.5,
				"Gloves_RiotGloves", 0.5,
                "HandTorch", 3,
				"Hat_GasMask",0.1,
				"Hat_NBCmask",0.1,
				"RogueMask", 0.1,
                "Mask_HECU", 0.1,
				"Hat_SwatGasMask", 0.1,
		}
		},
	
	Vest_Hunting_Grey = { -- stores
		rolls = 1,
		items = {
				"Leatherdad",1,
				"SAK",1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
                "HandTorch", 1,
				"Lighter",1,
				"Matches",1,
				"Cigarettes",1,
		}
		},
	
	Vest_Hunting_Orange = { -- stores
		rolls = 1,
		items = {
				"Leatherdad",1,
				"SAK",1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
                "HandTorch", 1,
				"Lighter",1,
				"Matches",1,
				"Cigarettes",1,
		}
		},
	
	Vest_Hunting_Camo = { -- stores
		rolls = 1,
		items = {
				"Leatherdad",1,
				"SAK",1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
                "HandTorch", 1,
				"Lighter",1,
				"Matches",1,
				"Cigarettes",1,
		}
		},
	
	Vest_Hunting_CamoGreen = { -- stores
		rolls = 1,
		items = {
				"Leatherdad",1,
				"SAK",1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
				"ShotgunShells",5,
				"223Bullets",5,
				"308Bullets",5,
                "HandTorch", 1,
				"Lighter",1,
				"Matches",1,
				"Cigarettes",1,
		}
		},
	
	Vest_Foreman = { -- stores
		rolls = 1,
		items = {
                "Bandaid", 1,
                "Bandage", 1,
                "AlcoholWipes", 1,
                "HandTorch", 3,
                "Screwdriver", 4,
				"Wrench",1,
                "Pen", 3,
                "BluePen", 1,
                "RedPen", 1,
                "Pencil", 3,
                "Eraser", 2,
                "Paperclip", 1,
                "SheetPaper2", 3,
                "Glasses_SafetyGoggles", 3,
                "Hat_DustMask", 4,
                "Hat_EarMuff_Protectors", 3,
				"Notebook",4,
				"Lighter",1,
				"Matches",1,
				"Cigarettes",1,
                "Radio.WalkieTalkie2",10,
                "Radio.WalkieTalkie3",2,
								
				"spraypaint.SpraycanWhite",1,
				"spraypaint.SpraycanRed",1,
				"spraypaint.SpraycanOrange",1,
				"spraypaint.SpraycanYellow",1,
				
				"Measuring_Tape",5,
				"Leatherdad",0.1,
				"SAK",1,
				
				"CheapSpeed",1,			
				"CokeBaggie",1,
				"EmptyCokeBaggie", 1,
		}
		},
	
	Suitcase = { -- stores
		rolls = 1,
		items = {           
				"SAK",0.1,				
				"CheapSpeed",0.1,			
				"CokeBaggie",0.1,
				
				"Base.PornoMag1",  0.1,
				"Base.PornoMag2",  0.1,
				"Base.PornoMag3",  0.1,
				"Base.PornoMag4",  0.1,
				"Base.PornoMag5",  0.1,
				"Base.PornoMag6",  0.1,
				"Base.HottieZ",  0.1,
				
				"AmericanGunsSpeedloadingSpecial",0.1,
				"FreewheelinMagazine",0.1,
				"MansHealth",0.1,
				"MercMagazineKnifeFightingSpecialIssue",0.1,
				"ModernDance",01,
				"PoliceBatonManual",0.1,
				"RunningLife",0.1,
				"SecretsOfTheShinobi",0.1,
				"SpicyNurseStories",01,
				"TwoWheelSlutsGettingGreasy",0.1,
				"VietCongTraps",0.1,
		}
		},
		
	Briefcase = { -- stores
		rolls = 1,
		items = {   				
				"CheapSpeed",0.1,			
				"CokeBaggie",0.1,
				
				"Base.PornoMag1",  0.1,
				"Base.PornoMag2",  0.1,
				"Base.PornoMag3",  0.1,
				"Base.PornoMag4",  0.1,
				"Base.PornoMag5",  0.1,
				"Base.PornoMag6",  0.1,
				"Base.HottieZ",  0.1,
				
				"MansHealth",0.1,
				"ModernDance",01,
				"RunningLife",0.1,
				"SpicyNurseStories",01,
				"TwoWheelSlutsGettingGreasy",0.1,
		}
		},		
	Purse = { -- stores
		rolls = 1,
		items = {      
				"SAK",0.1,	  				
				"CheapSpeed",0.1,			
				"CokeBaggie",0.1,
		}
		},	
	Handbag = { -- stores
		rolls = 1,
		items = {      
				"SAK",0.1,	  				
				"CheapSpeed",0.1,			
				"CokeBaggie",0.1,
		}
		},
		
	Bag_NormalHikingBag = { -- stores
		rolls = 1,
		items = { 	
				"Leatherdad",1,
				"SAK",1,
				"Canteen",1,
				"Canteenfull",1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
		}
		},
		
	Bag_BigHikingBag = { -- stores
		rolls = 1,
		items = { 	
				"Leatherdad",1,
				"SAK",1,
				"Canteen",1,
				"Canteenfull",1,
				"Compass",1,
				"Compass2",1,
				"CliponCompass",1,
				"PLGR",1,
                "MRE", 1,
		}
		},

}

table.insert(Distributions, distributionTable);
