require "Items/ProceduralDistributions"
-- M998SpareMount_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998SpareMount_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998SpareMount_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998SpareMount_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998SpareMount_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.M998SpareMount_Item");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.5);
-- V101Tire2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.V101Tire2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.V101Tire2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.V101Tire2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.V101Tire2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5);
-- M998Muffler1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998Muffler1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998Muffler1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998Muffler1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998Muffler1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.4);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.M998Muffler1_Item");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.4);
-- M998Muffler2_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998Muffler2_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998Muffler2_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998Muffler2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998Muffler2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.3);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.M998Muffler2_Item");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.3);
-- M998Bullbar1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998Bullbar1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998Bullbar1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998Bullbar1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998Bullbar1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.4);
-- M998Bullbar2_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998Bullbar2_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998Bullbar2_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998Bullbar2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998Bullbar2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.3);
-- leafSuspension2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.leafSuspension2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.leafSuspension2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.leafSuspension2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.leafSuspension2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.4);
-- M998Mudflaps1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998Mudflaps1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998Mudflaps1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998Mudflaps1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998Mudflaps1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.4);
-- M998CarFrontDoorArmor1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998CarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998CarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998CarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998CarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
-- M998CarFrontDoorArmor2_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.M998CarFrontDoorArmor2_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.M998CarFrontDoorArmor2_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.M998CarFrontDoorArmor2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.M998CarFrontDoorArmor2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);