require "Vehicles/VehicleDistributions"

table.insert(VehicleDistributions.Police.TruckBed.items, "Vest_RogueVest_Black")
table.insert(VehicleDistributions.Police.TruckBed.items, 0.8)
table.insert(VehicleDistributions.Police.TruckBed.items, "HolsterPLL2")
table.insert(VehicleDistributions.Police.TruckBed.items, 3)
-- table.insert(VehicleDistributions.Police.TruckBed.items, "BeltRig")
-- table.insert(VehicleDistributions.Police.TruckBed.items, 2)
table.insert(VehicleDistributions.Police.TruckBed.items, "TacticalWaistBagBack_Black")
table.insert(VehicleDistributions.Police.TruckBed.items, 0.5)
-- table.insert(VehicleDistributions.Police.TruckBed.items, "ClericPants")
-- table.insert(VehicleDistributions.Police.TruckBed.items, 0.5)
table.insert(VehicleDistributions.Police.TruckBed.items, "HATELA")
table.insert(VehicleDistributions.Police.TruckBed.items, 0.2)
table.insert(VehicleDistributions.Police.TruckBed.items, "medbag2")
table.insert(VehicleDistributions.Police.TruckBed.items, 1)
table.insert(VehicleDistributions.Police.TruckBed.items, "strapchest_Black")
table.insert(VehicleDistributions.Police.TruckBed.items, 0.5)
table.insert(VehicleDistributions.Police.TruckBed.items, "MVest_Black")
table.insert(VehicleDistributions.Police.TruckBed.items, 0.5)
table.insert(VehicleDistributions.Police.TruckBed.items, "FlatCap")
table.insert(VehicleDistributions.Police.TruckBed.items, 1)

table.insert(VehicleDistributions.DoctorTruckBed.items, "medbag")
table.insert(VehicleDistributions.DoctorTruckBed.items, 0.4)
table.insert(VehicleDistributions.DoctorTruckBed.items, "TacticalWaistBagBackMed")
table.insert(VehicleDistributions.DoctorTruckBed.items, 0.3)
table.insert(VehicleDistributions.DoctorTruckBed.items, "Bag_ParaMedic")
table.insert(VehicleDistributions.DoctorTruckBed.items, 0.6)

table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Hat_Altyn")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.6)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "WetSuit")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)	
-- table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Shoes_Rogue")
-- table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
-- table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Gloves_Rogue")
-- table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Vest_RogueVest")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Vest_WitchyCarrier")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.8)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "RogueMask")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "strapchest")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "MVest")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "TacticalWaistBagBack")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.4)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "TacticalWaistBagBackMed")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.4)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "HolsterPLL2M")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 2)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "medbag")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.6)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "medbag2")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.6)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "FlatCap")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 1.5)
-- table.insert(VehicleDistributions.SurvivalistTruckBed.items, "smallback")
-- table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.8)