-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["location_business_office_generic_01_51"] = {{ name = "other", chance = 3, usage = "", tiles = {"fanta_writting_01_21", "fanta_writting_01_13", "fanta_writting_01_14", "fanta_writting_01_9", "fanta_writting_01_11", "fanta_writting_01_19"} }}
overlayMap["location_business_office_generic_01_54"] = {{ name = "other", chance = 3, usage = "", tiles = {"fanta_writting_01_20", "fanta_writting_01_12", "fanta_writting_01_15", "fanta_writting_01_18", "fanta_writting_01_16", "fanta_writting_01_10", "fanta_writting_01_8"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
